config/routes.rb
Rails.application.routes.draw do
  # ルートパス
  root to: 'homes#top'

  # ユーザ認証機能のルーティング
  devise_for :users

  # ゲストユーザ
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  # ユーザのルーティング
  resources :users, only: [:show, :edit, :update] do
    # フォロー機能のルーティング
    resource :relationships, only: [:create, :destroy]
    get 'relationships/followings' => 'relationships#followings', as: 'follows'
    get 'relationships/followers' => 'relationships#followers', as: 'followers'
  end

  # 投稿（鉄道）に関するルーティング
  resources :trains do
    # いいね機能のルーティング
    resource :favorites, only: [:create, :destroy]

    # コメント機能のルーティング
    resources :train_comments, only: [:create, :destroy]
  end

  # いいね一覧画面のルーティング
  resources :favorites, only: [:index]

  # チャットルームのルーティング
  resources :rooms, only: [:index, :show, :create]

  # メッセージのルーティング
  resources :messages, only: [:create, :destroy]

  # 通知のルーティング
  get 'notifications/index' => 'notifications#index', as: 'notifications'
  delete 'notifications/destroy_all' => 'notifications#destroy_all', as: 'notification_all_delete'

  # 検索のルーティング
  get 'searches/search' => 'searches#search', as: 'search'
end

app/views/shared/_chat-link.html.erb
<!-- 自分のマイページかどうかで表示を分ける -->
<% if @user.id == current_user.id %>
<% else %>

  <!-- 既にチャットを始めているかどうかで表示を分ける -->
  <% if @is_room == true %>
    <%= link_to "チャットへ", room_path(@room_id), class: "btn btn-secondary" %>
  <% else %>
    <%= form_with model: room, url: rooms_path, local:true do |f| %>
      <%= fields_for entry do |e| %>
        <%= e.hidden_field :user_id, :value => user.id %>
      <% end %>
      <%= f.submit "チャットを始める", class: "btn btn-secondary" %>
    <% end %>
  <% end %>
<% end %>

app/views/shared/_edit-form.html.erb
<!-- 投稿内容編集フォーム -->
<%= form_with model: train,local:true do |f| %>
  <%= render 'shared/errors', obj: train %>
  <div class="form-group">
    <%= f.label :画像, class: "font-weight-bold" %>
    <%= f.file_field :train_image, class: "form-control-file train_image" %>
  </div>
  <div class="form-group">
    <%= f.label :路線, class: "font-weight-bold" %><br>
    <%= f.select :line, Train.lines.keys.to_a %>
  </div>
  <div class="form-group">
    <%= f.label :本文, class: "font-weight-bold" %>
    <%= f.text_area :body, class: 'form-control train_body', size: "90x6" %>
  </div>
  <div class="form-group">
    <%= f.submit '更新する', class: 'btn btn-success' %>　|　<%= link_to '投稿を削除する', train_path(@train.id), method: :delete, data: { confirm: 'この投稿データを削除しますか？' }, class: "btn btn-danger" %>
  </div>
<% end %>

app/views/shared/_header.html.erb
<!-- headerリスト -->
<header class="sticky-top">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">

      <!-- Top画面へのリンクを表示 -->
      <a href="/" class="home-icon navbar-brand text-white" data-turbolinks="false"><%= image_tag asset_path "電車アイコン.png" %></a>

      <!-- ユーザがログイン時に名前を表示する -->
      <% if user_signed_in? %>
        <p class="user-name">ようこそ、<%= current_user.name %> さん！</p>
      <% end %>
      <p id="notice"><%= notice %></p>

      <!-- ユーザログイン時に検索窓を表示 -->
      <% if user_signed_in? %>
        <div class="search-form">
          <%= render 'shared/searches/search-form' %>
        </div>
      <% end %>

      <!-- ハンバーガーバーボタン -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">

        <!-- ログイン/非ログイン時でヘッダーリストを分岐 -->
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <%= render 'shared/user-signin' %>
          <% else %>
            <%= render 'shared/nouser' %>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_message-form.html.erb
<!-- メッセージ送信フォーム -->
<%= form_with model: message, url: messages_path, method: :post, remote: true do |f| %>
  <%= f.text_area :message, :placeholder => "メッセージを入力して下さい" , size: '70x3' %>
  <%= f.hidden_field :room_id, :value => @room.id %><br>
  <div class="messsage-submit-btn text-center">
    <%= f.submit "投稿する", class: "btn btn-success" %>
  </div>
<% end %>

app/views/shared/_new-trains.html.erb
<!-- 非ユーザの時、新着投稿8件表示する -->
<div class="d-flex flex-row flex-wrap">
  <% trains.first(8).each do |train| %>
    <div class="card-deck mb-5 mr-2">
      <div class="card">
        <div class="card-image">
          <%= link_to train_path(train.id) do %>
            <%= attachment_image_tag train, :train_image, width: "100%" , height: "150px", format: 'jpg', fallback: "no_image.jpg" %>
          <% end %>
        </div>
        <div class="card-body">
          <div class="card-name font-weight-bold">
            <%= train.user.name %>
          </div>
          <div class="card-train-line font-weight-bold"><%= train.line %></div>
          <div class="card-train-body"><%= train.body %></div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_nouser.html.erb
<!-- 非ログイン時のヘッダー表示 -->
<li class="balloonoya">
  <%= link_to '', trains_path, class: 'fas fa-folder nav-link text-white' %>
  <span class="balloon">記事一覧</span>
</li>
<li class="balloonoya">
  <%= link_to '', new_user_registration_path, method: :get, class: 'fas fa-user-plus nav-link text-white' %>
  <span class="balloon">新規登録</span>
</li>
<li class="balloonoya">
  <%= link_to '', users_guest_sign_in_path, method: :post, class: 'fas fas fa-user-circle nav-link text-white' %>
  <span class="balloon">ゲストログイン</span>
</li>
<li class="balloonoya">
  <%= link_to '', new_user_session_path, method: :get, class: 'fas fa-sign-in-alt nav-link text-white' %>
  <span class="balloon">ログイン</span>
</li>

app/views/shared/_search-users.html.erb
<!-- ユーザ検索結果表示画面 -->
<table class="table">

  <!-- 検索結果で表示を分ける -->
  <% if users.empty? %>
    <h3 class="no-user">該当するユーザはいません</h3>
  <% else %>
    <% users.each do |user| %>
      <tr>
        <td>
          <%= attachment_image_tag(user, :profile_image, size: "50x50", fallback: "no_image.jpg") %>
        </td>
        <td>
          <%= link_to user_path(user) do %>
            <%= user.name %>
          <% end %>
        </td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td class="follower-count_<%= user.id %>">フォロワー数: <%= user.followers.count %></td>
        <% if current_user != user %>
          <td class="follow_<%= user.id %>"><%= render 'shared/follow-btn', user: user %></td>
        <% end %>
      </tr>
    <% end %>
  <% end %>
</table>

app/views/shared/_timeline.html.erb
<!-- ユーザログイン時、タイムラインを16件表示する -->
<div class="d-flex flex-row flex-wrap">
  <% follow_users_trains.first(16).each do |train| %>
    <div class="card-deck mb-5 mr-2">
      <div class="card">
        <div class="card-image">
          <%= link_to train_path(train.id) do %>
            <%= attachment_image_tag train, :train_image, width: "100%" , height: "150px", format: 'jpg', fallback: "no_image.jpg" %>
          <% end %>
        </div>

        <div class="card-body">
          <div class="card-name font-weight-bold">
            <% if user_signed_in? %>
              <%= link_to user_path(train.user) do %>
                <%= train.user.name %>
              <% end %>
            <% else %>
              <%= train.user.name %>
            <% end %>
          </div>
          <div class="card-train-line font-weight-bold"><%= train.line %></div>
          <div class="card-train-body"><%= train.body %></div>
          <% if user_signed_in? %>
            <div class="train-activities">
              <div id="favorite_<%= train.id %>"><%= render 'shared/favorite-btn', train: train %></div>
              <div class="comment-count">コメント数： <%= train.train_comments.count %></div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_train-edit-form.html.erb
<!-- 投稿内容編集フォーム -->
<%= form_with model: train,local:true do |f| %>
  <%= render 'shared/errors', obj: train %>
  <div class="form-group">
    <%= f.label :画像, class: "font-weight-bold" %>
    <%= f.attachment_field :train_image, class: "form-control-file train_image" %>

    <!-- 画像のプレビューを表示 -->
    <%= attachment_image_tag train, :train_image, size: "475x300", format: 'jpg', fallback: "no_image.jpg", class: "image-preview" %>
  </div>
  <div class="form-group">
    <%= f.label :路線, class: "font-weight-bold" %><br>
    <%= f.select :line, Train.lines.keys.to_a %>
  </div>
  <div class="form-group">
    <%= f.label :本文, class: "font-weight-bold" %>
    <%= f.text_area :body, class: 'form-control train_body', size: "90x6" %>
  </div>
  <div class="form-group">
    <%= f.submit '更新する', class: 'btn btn-success' %>　|　<%= link_to '投稿を削除する', train_path(@train.id), method: :delete, data: { confirm: 'この投稿データを削除しますか？' }, class: "btn btn-danger" %>
  </div>
<% end %>

app/views/shared/_train-new-form.html.erb
<!-- 新規投稿フォーム -->
<%= form_with model: train, url: trains_path, method: :post, local:true do |f| %>
  <%= render 'shared/errors', obj: train %>
  <div class="form-group">
    <%= f.label :画像, class: "font-weight-bold" %>
    <%= f.attachment_field :train_image, class: "form-control-file train_image" %>

    <!-- 画像のプレビューを表示 -->
    <%= attachment_image_tag train, :train_image, size: "475x300", format: 'jpg', fallback: "no_image.jpg", class: "image-preview" %>
  </div>
  <div class="form-group">
    <%= f.label :路線, class: "font-weight-bold" %><br>
    <%= f.select :line, Train.lines.keys.to_a %>
  </div>
  <div class="form-group">
    <%= f.label :本文, class: "font-weight-bold" %>
    <%= f.text_area :body, size: '90x8' %>
  </div>
  <div class="form-group">
    <%= f.submit "投稿", class: "btn btn-success" %>
  </div>
<% end %>

app/views/shared/_user-edit-form.html.erb
<!-- ユーザー情報編集フォーム -->
<%= form_with model: user, url: user_path, local:true do |f| %>
   <%= render 'shared/errors', obj: user %>
   <div class="form-group">
     <%= f.label :プロフィール画像, class: "font-weight-bold" %>
     <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>

     <!-- 画像のプレビューを表示 -->
     <%= attachment_image_tag user, :profile_image, size: "475x300", format: 'jpg', fallback: "no_image.jpg", class: "image-preview" %>
   </div>
   <div class="form-group">
     <%= f.label :ユーザ名, class: "font-weight-bold" %>
     <%= f.text_field :name, class: "form-control name" %>
   </div>
   <div class="form-group">
     <%= f.label :紹介文, class: "font-weight-bold" %>
     <%= f.text_area :introduction, class: "form-control introduction", size: '90x8' %>
   </div>
   <div class="form-group">
     <%= f.submit '更新する', class: 'btn btn-success' %>　|　<%= link_to 'マイページへ', user_path(@user), class: "btn btn-info" %>
   </div>
<% end %>

app/views/shared/_user-info.html.erb
<!-- ユーザの情報を表示 -->
<div class="user-image">
  <%= attachment_image_tag(user, :profile_image, size: "100x100", format: 'jpg', fallback: "no_image.jpg") %>
</div>
<table class="user-detail">
  <th>ユーザ名</th>
  <th>　</th>
  <th><%= user.name %></th>
</table>
<section class="introduction">
  <p>
   <strong>紹介文</strong><br>
   <%= user.introduction %>
  </p>
</section>
<table>
  <tr>
	  <th>フォロー</th>
	  <th>　</th>
	  <th><%= link_to user.followings.count, user_follows_path(user.id) %></th>
  </tr>
  <tr>
	  <th>フォロワー</th>
	  <th>　</th>
	  <th class="follow-count"><%= link_to user.followers.count, user_followers_path(user.id) %></th>
  </tr>
</table>

<!-- 自分のマイページを見ているかで表示を分ける -->
<% if current_user != user %>
  <div class="follow_<%= user.id %>">
    <%= render 'shared/follow-btn', user: user %>
  </div>

  <div class="chat-link">
    <%= render 'shared/chat-link', user: @user, room: @room, entry: @entry %>
  </div>
<% else %>

  <!-- ゲストログインしている時は、ユーザ情報編集ボタンを表示させない -->
  <% unless current_user.name == "guest" %>
    <div class="edit-link">
      <%= link_to '',edit_user_path(user), class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
    </div>
  <% end %>
<% end %>

app/views/shared/_user-signin.html.erb
<!-- ユーザログイン時のヘッダー表示 -->
<li class="balloonoya">
  <%= link_to notifications_path(current_user) do %>
    <% if unchecked_notifications.any? %>
      <i class="fas fa-bell nav-link text-warning"></i>
      <span class="balloon">通知あり</span>
    <% else %>
      <i class="fas fa-bell nav-link text-white"></i>
      <span class="balloon">通知一覧</span>
    <% end %>
  <% end %>
</li>
<li class="balloonoya">
  <%= link_to '', rooms_path(current_user), class: "fas fa-envelope nav-link text-white" %>
  <span class="balloon">チャット一覧</span>
</li>
<li class="balloonoya">
  <%= link_to '', favorites_path(current_user), class: 'fas fa-star nav-link text-white' %>
  <span class="balloon">いいね一覧</span>
</li>
<li class="balloonoya">
  <%= link_to '', user_path(current_user), class: 'fas fa-user nav-link text-white' %>
  <span class="balloon">マイページ</span>
</li>
<li class="balloonoya">
  <%= link_to '', trains_path, class: 'fas fa-folder nav-link text-white' %>
  <span class="balloon">記事一覧</span>
</li>
<li class="balloonoya">
  <%= link_to '', new_train_path, method: :get, class: 'fas fa-share-square nav-link text-white' %>
  <span class="balloon">新規投稿</span>
</li>
<li class="balloonoya">
  <%= link_to '', destroy_user_session_path, method: :delete, class: 'fas fa-sign-out-alt nav-link text-white' %>
  <span class="balloon">ログアウト</span>
</li>

app/views/shared/_user-trains.html.erb
<!-- 投稿した記事を表示する -->
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>路線</th>
      <th>本文</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% trains.each do |train| %>
      <tr>
        <td>
          <%= link_to train_path(train.id) do %>
            <%= attachment_image_tag(train, :train_image, size: "50x50", format: 'jpg', fallback: "no_image.jpg") %>
          <% end %>
        </td>
        <td><%= train.line %></td>
        <td><%= train.body %></td>
        <% unless @user == current_user %>
          <td id="favorite_<%= train.id %>"><%= render 'shared/favorite-btn', train: train %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>