config/routes.rb
Rails.application.routes.draw do
  # ルートパス
  root to: 'homes#top'

  # ユーザ認証機能のルーティング
  devise_for :users

  # ゲストユーザ
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  # ユーザのルーティング
  resources :users, only: [:show, :edit, :update] do
    # フォロー機能のルーティング
    resource :relationships, only: [:create, :destroy]
    get 'relationships/followings' => 'relationships#followings', as: 'follows'
    get 'relationships/followers' => 'relationships#followers', as: 'followers'
  end

  # 投稿（鉄道）に関するルーティング
  resources :trains do
    # いいね機能のルーティング
    resource :favorites, only: [:create, :destroy]

    # コメント機能のルーティング
    resources :train_comments, only: [:create, :destroy]
  end

  # いいね一覧画面のルーティング
  resources :favorites, only: [:index]

  # チャットルームのルーティング
  resources :rooms, only: [:index, :show, :create]

  # メッセージのルーティング
  resources :messages, only: [:create, :destroy]

  # 通知のルーティング
  get 'notifications/index' => 'notifications#index', as: 'notifications'
  delete 'notifications/destroy_all' => 'notifications#destroy_all', as: 'notification_all_delete'

  # 検索のルーティング
  get 'searches/search' => 'searches#search', as: 'search'
end

app/models/train_comment.rb
class TrainComment < ApplicationRecord
  # コメントのモデル

  # アソシエーション
  belongs_to :user
  belongs_to :train
  has_many :notifications, dependent: :destroy

  # バリデーション
  validates :comment, length: { maximum: 140 }, presence: true
end

app/controllers/train_comments_controller.rb
class TrainCommentsController < ApplicationController
  before_action :authenticate_user!

  # コメント機能のコントローラー

  # コメント投稿機能
  def create
    @train = Train.find(params[:train_id])
    @train_comment = TrainComment.new(train_comment_params)
    @train_comment.train_id = @train.id
    @train_comment.user_id = current_user.id
    if @train_comment.save
      @train.create_notification_train_comment!(current_user, @train_comment.id)
    else
      render 'error'
    end
  end

  # コメント削除機能
  def destroy
    @train = Train.find(params[:train_id])
    @train_comment = TrainComment.find(params[:id])
    @train_comment.destroy
  end

  # ストロングパラメーター
  private

  def train_comment_params
    params.require(:train_comment).permit(:comment)
  end
end

app/helpers/train_comments_helper.rb
module TrainCommentsHelper
end

app/views/shared/train_comments/_comment-form.html.erb
<%= form_with model:[train, train_comment], url: train_train_comments_path(train), method: :post, remote: true do |f| %>
  <%= f.text_area :comment %><br>
  <%= f.submit '送信', class: "btn btn-success" %>
<% end %>

app/views/shared/train_comments/_train_comment-index.html.erb
<!-- コメントを表示 -->
<table class="train-comments">
  <% train.train_comments.each do |train_comment| %>
    <tr>
      <td class="font-weight-bold"><%= train_comment.user.name %></td>
      <td>　</td>
      <td><%= train_comment.comment %></td>
      <td>　</td>
      <% if train_comment.user == current_user %>
        <td><%= link_to '削除', train_train_comment_path(train_comment.train_id, train_comment.id), method: :delete, remote: true, class: "btn btn-sm btn-danger", data: { confirm: 'コメントを削除しますか？' } %></td>
      <% end %>
    </tr>
  <% end %>
</table>

<div id="comment-error">
  <%= render 'shared/errors', obj: @train_comment %>
</div>

<!-- コメント入力フォーム -->
<section class="comment-form mx-auto">
  <%= render 'shared/train_comments/comment-form', train: train, train_comment: @train_comment %>
</section>